// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsxfzpfhwyzltbcuygdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zeGZ6cGZod3l6bHRiY3V5Z2R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTMxMjgsImV4cCI6MjA3Mzc4OTEyOH0.53KO1upqfRUYKdv2WcemxwM4eNM2X0FWPxEa3tF1Tqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});